# Forward selection

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import sklearn
import seaborn as sns
import xlrd
import time
import statsmodels.api as sm
from sklearn.preprocessing import PolynomialFeatures

In [2]:
data=pd.read_excel('Data/Mini Project EFSA.xlsx')
data.rename(columns={'sex \n(0=M, 1=F)':'sex'}, inplace=True)
data

    response  number of animals    SD  dose  sex  endpoint
0      570.4                  9  75.6     0    0         1
1      548.5                 10  44.3    30    0         1
2      533.0                 10  72.3   100    0         1
3      488.1                  9  42.5   150    0         1
4      329.8                 10  46.8     0    1         1
5      319.7                 10  24.3    30    1         1
6      293.3                 10  20.1   100    1         1
7      312.4                 10  43.1   150    1         1
8       45.2                  9   1.5     0    0         2
9       44.6                 10   1.7    30    0         2
10      43.0                 10   3.8   100    0         2
11      42.8                  9   1.7   150    0         2
12      44.7                 10   1.3     0    1         2
13      44.1                 10   1.6    30    1         2
14      41.5                 10   1.6   100    1         2
15      42.1                 10   1.2   150    1         2
16      18.3                  9   0.5     0    0         3
17      17.9                 10   0.5    30    0         3
18      16.5                 10   0.6   100    0         3
19      16.3                  9   0.8   150    0         3
20      19.1                 10   0.5     0    1         3
21      19.0                 10   0.4    30    1         3
22      17.9                 10   0.5   100    1         3
23      17.3                 10   0.6   150    1         3

# Forward selection

In [3]:
import funzioni as fn
data_Endpoint1 = data[data.endpoint == 1]
data_Endpoint2 = data[data.endpoint == 2]
data_Endpoint3 = data[data.endpoint == 3]

## Forward selection endpoint1

In [11]:
Y = data_Endpoint1.response
weights = data.SD
X = data_Endpoint1.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint1 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint1)

Processed  3 models on 1 predictors in 0.02298736572265625 seconds.
Processed  2 models on 2 predictors in 0.013991594314575195 seconds.
Processed  1 models on 3 predictors in 0.008992433547973633 seconds.
Total elapsed time: 0.06998014450073242 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,123209.466339,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,6222.696768,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]"
3,3908.060536,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]"

In [13]:
print(group_of_models_endpoint1['model'])
fig = sm.graphics.plot_partregress_grid(group_of_models_endpoint1['model'])

             RSS                                              model  \
1  123209.466339  <statsmodels.regression.linear_model.Regressio...
2    6222.696768  <statsmodels.regression.linear_model.Regressio...
3    3908.060536  <statsmodels.regression.linear_model.Regressio...

  number_of_predictors             name_of_predictors
1                    1             [number of animals]
2                    2        [number of animals, sex]
3                    3  [number of animals, sex, dose]

AttributeError: 'Series' object has no attribute 'model'

## Forward selection endpoint2

In [6]:
Y = data_Endpoint2.response
weights = data.SD
X = data_Endpoint2.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint2 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint2)

Processed  3 models on 1 predictors in 0.02298116683959961 seconds.
Processed  2 models on 2 predictors in 0.02201247215270996 seconds.
Processed  1 models on 3 predictors in 0.00799703598022461 seconds.
Total elapsed time: 0.0829458236694336 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,51.303412,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,34.458343,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]"
3,27.729987,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]"

## Forward selection endpoint3

In [7]:
Y = data_Endpoint3.response
weights = data.SD
X = data_Endpoint3.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint3 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint3)

Processed  3 models on 1 predictors in 0.01700758934020996 seconds.
Processed  2 models on 2 predictors in 0.015992403030395508 seconds.
Processed  1 models on 3 predictors in 0.0050008296966552734 seconds.
Total elapsed time: 0.061302900314331055 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,9.019606,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,4.786838,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, dose]"
3,4.724882,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, dose, sex]"