# Forward selection

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import sklearn
import seaborn as sns
import xlrd
import time
import statsmodels.api as sm
from sklearn.preprocessing import PolynomialFeatures

In [3]:
data=pd.read_excel('Data/Mini Project EFSA.xlsx')
data.rename(columns={'sex \n(0=M, 1=F)':'sex'}, inplace=True)
data

    response  number of animals    SD  dose  sex  endpoint
0      570.4                  9  75.6     0    0         1
1      548.5                 10  44.3    30    0         1
2      533.0                 10  72.3   100    0         1
3      488.1                  9  42.5   150    0         1
4      329.8                 10  46.8     0    1         1
5      319.7                 10  24.3    30    1         1
6      293.3                 10  20.1   100    1         1
7      312.4                 10  43.1   150    1         1
8       45.2                  9   1.5     0    0         2
9       44.6                 10   1.7    30    0         2
10      43.0                 10   3.8   100    0         2
11      42.8                  9   1.7   150    0         2
12      44.7                 10   1.3     0    1         2
13      44.1                 10   1.6    30    1         2
14      41.5                 10   1.6   100    1         2
15      42.1                 10   1.2   150    1         2
16      18.3                  9   0.5     0    0         3
17      17.9                 10   0.5    30    0         3
18      16.5                 10   0.6   100    0         3
19      16.3                  9   0.8   150    0         3
20      19.1                 10   0.5     0    1         3
21      19.0                 10   0.4    30    1         3
22      17.9                 10   0.5   100    1         3
23      17.3                 10   0.6   150    1         3

# Forward selection

In [4]:
import funzioni as fn
data_Endpoint1 = data[data.endpoint == 1]
data_Endpoint2 = data[data.endpoint == 2]
data_Endpoint3 = data[data.endpoint == 3]

## Forward selection endpoint1

In [5]:
Y = data_Endpoint1.response
weights = data.SD
X = data_Endpoint1.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint1 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint1)

Processed  3 models on 1 predictors in 0.029280662536621094 seconds.
Processed  2 models on 2 predictors in 0.007995843887329102 seconds.
Processed  1 models on 3 predictors in 0.00499725341796875 seconds.
Total elapsed time: 0.061685800552368164 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,123209.466339,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,6222.696768,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]"
3,3908.060536,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]"

In [21]:
model1 = group_of_models_endpoint1["model"][1]
display(model1.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 WLS Regression Results
=======================================================================================
Dep. Variable:               response   R-squared (uncentered):                   0.920
Model:                            WLS   Adj. R-squared (uncentered):              0.909
Method:                 Least Squares   F-statistic:                              80.67
Date:                Fri, 27 Nov 2020   Prob (F-statistic):                    4.32e-05
Time:                        18:21:51   Log-Likelihood:                         -49.920
No. Observations:                   8   AIC:                                      101.8
Df Residuals:                       7   BIC:                                      101.9
Df Model:                           1
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
number of animals    43.1673      4.806      8.982      0.000      31.803      54.532
==============================================================================
Omnibus:                        4.980   Durbin-Watson:                   0.375
Prob(Omnibus):                  0.083   Jarque-Bera (JB):                1.084
Skew:                           0.100   Prob(JB):                        0.581
Kurtosis:                       1.208   Cond. No.                         1.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [40]:
data_plot = data_Endpoint1.drop(columns=["SD", "dose", "sex", "endpoint"])
#display(data_plot)
sm.graphics.plot_partregress("response", "number of animals", data= data_plot, obs_labels=False)
#group_of_models_endpoint1.plot(x = 'number_of_predictors', y = 'RSS')

TypeError: plot_partregress() missing 1 required positional argument: 'exog_others'

### AIC, BIC, MSE e ADJ_RSQUARE endpoint1

In [7]:
group_of_models_endpoint1 = fn.compute_criteria(group_of_models_endpoint1)
group_of_models_endpoint1

,RSS,model,number_of_predictors,name_of_predictors,aic,bic,mse,adj_rsquare
1,123209.466339,<statsmodels.regression.linear_model.Regressio...,1,[number of animals],101.840614,101.920055,192891.725,0.908750
2,6222.696768,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]",79.955153,80.114037,192891.725,0.994623
3,3908.060536,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]",78.233856,78.472181,192891.725,0.995948

## Forward selection endpoint2

In [8]:
Y = data_Endpoint2.response
weights = data.SD
X = data_Endpoint2.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint2 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint2)

Processed  3 models on 1 predictors in 0.016995668411254883 seconds.
Processed  2 models on 2 predictors in 0.010993719100952148 seconds.
Processed  1 models on 3 predictors in 0.00499725341796875 seconds.
Total elapsed time: 0.05296945571899414 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,51.303412,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,34.458343,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]"
3,27.729987,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]"

### AIC, BIC, MSE e ADJ_RSQUARE endpoint2

In [9]:
group_of_models_endpoint2 = fn.compute_criteria(group_of_models_endpoint2)
group_of_models_endpoint2

,RSS,model,number_of_predictors,name_of_predictors,aic,bic,mse,adj_rsquare
1,51.303412,<statsmodels.regression.linear_model.Regressio...,1,[number of animals],39.569542,39.648984,1893.825,0.996130
2,34.458343,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, sex]",38.385493,38.544376,1893.825,0.996967
3,27.729987,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, sex, dose]",38.647599,38.885924,1893.825,0.997072

## Forward selection endpoint3

In [10]:
Y = data_Endpoint3.response
weights = data.SD
X = data_Endpoint3.drop(columns=["response", "SD", "endpoint"])
group_of_models_endpoint3 = fn.mainForward(X, Y, weights)
display(group_of_models_endpoint3)

Processed  3 models on 1 predictors in 0.022987842559814453 seconds.
Processed  2 models on 2 predictors in 0.01798868179321289 seconds.
Processed  1 models on 3 predictors in 0.006998538970947266 seconds.
Total elapsed time: 0.0839536190032959 seconds.

,RSS,model,number_of_predictors,name_of_predictors
1,9.019606,<statsmodels.regression.linear_model.Regressio...,1,[number of animals]
2,4.786838,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, dose]"
3,4.724882,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, dose, sex]"

### AIC, BIC, MSE e ADJ_RSQUARE endpoint3

In [11]:
group_of_models_endpoint3 = fn.compute_criteria(group_of_models_endpoint3)
group_of_models_endpoint3

,RSS,model,number_of_predictors,name_of_predictors,aic,bic,mse,adj_rsquare
1,9.019606,<statsmodels.regression.linear_model.Regressio...,1,[number of animals],25.662690,25.742131,317.34375,0.995940
2,4.786838,<statsmodels.regression.linear_model.Regressio...,2,"[number of animals, dose]",22.594445,22.753328,317.34375,0.997486
3,4.724882,<statsmodels.regression.linear_model.Regressio...,3,"[number of animals, dose, sex]",24.490225,24.728550,317.34375,0.997022

## Backward selection