### Visualizzare i 6 grafici

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import sklearn
import seaborn as sns
import xlrd

In [10]:
data=pd.read_excel('Data/Mini Project EFSA.xlsx')
data

    response  number of animals    SD  dose  sex \n(0=M, 1=F)  endpoint
0      570.4                  9  75.6     0                 0         1
1      548.5                 10  44.3    30                 0         1
2      533.0                 10  72.3   100                 0         1
3      488.1                  9  42.5   150                 0         1
4      329.8                 10  46.8     0                 1         1
5      319.7                 10  24.3    30                 1         1
6      293.3                 10  20.1   100                 1         1
7      312.4                 10  43.1   150                 1         1
8       45.2                  9   1.5     0                 0         2
9       44.6                 10   1.7    30                 0         2
10      43.0                 10   3.8   100                 0         2
11      42.8                  9   1.7   150                 0         2
12      44.7                 10   1.3     0                 1         2
13      44.1                 10   1.6    30                 1         2
14      41.5                 10   1.6   100                 1         2
15      42.1                 10   1.2   150                 1         2
16      18.3                  9   0.5     0                 0         3
17      17.9                 10   0.5    30                 0         3
18      16.5                 10   0.6   100                 0         3
19      16.3                  9   0.8   150                 0         3
20      19.1                 10   0.5     0                 1         3
21      19.0                 10   0.4    30                 1         3
22      17.9                 10   0.5   100                 1         3
23      17.3                 10   0.6   150                 1         3